// <auto-generated />
using DataAccessLayer.Models.DataBaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251206194754_SlotTimes")]
    partial class SlotTimes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("DataAccessLayer.Models.AvailabilityDayModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("AvailabilityMonthId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("availability_month_id");

                    b.Property<int>("DayOfMonth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("day_of_month");

                    b.Property<string>("IntervalStr")
                        .HasColumnType("TEXT")
                        .HasColumnName("interval_str");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.HasKey("Id");

                    b.HasIndex("AvailabilityMonthId", "DayOfMonth")
                        .IsUnique()
                        .HasDatabaseName("ux_availability_day_month_day");

                    b.HasIndex(new[] { "AvailabilityMonthId", "DayOfMonth" }, "ix_avail_day_month");

                    b.HasIndex(new[] { "AvailabilityMonthId", "DayOfMonth" }, "ux_availability_day_month_day")
                        .IsUnique();

                    b.ToTable("availability_day", t =>
                        {
                            t.HasCheckConstraint("ck_availability_day_dom", "day_of_month BETWEEN 1 AND 31");

                            t.HasCheckConstraint("ck_availability_day_kind_interval", "((kind = 'INT' AND interval_str IS NOT NULL AND length(trim(interval_str)) >= 11) OR (kind IN ('ANY','NONE') AND interval_str IS NULL))");
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.AvailabilityMonthModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("employee_id");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER")
                        .HasColumnName("month");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "Year", "Month")
                        .IsUnique()
                        .HasDatabaseName("ux_availability_month_emp_year_month");

                    b.HasIndex(new[] { "EmployeeId", "Year", "Month" }, "ix_avail_month_emp");

                    b.HasIndex(new[] { "EmployeeId", "Year", "Month" }, "ux_availability_month_emp_year_month")
                        .IsUnique();

                    b.ToTable("availability_month", t =>
                        {
                            t.HasCheckConstraint("ck_availability_month_month", "month BETWEEN 1 AND 12");
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.ContainerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("container");
                });

            modelBuilder.Entity("DataAccessLayer.Models.EmployeeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_name");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.HasKey("Id");

                    b.ToTable("employee");
                });

            modelBuilder.Entity("DataAccessLayer.Models.ScheduleEmployeeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("employee_id");

                    b.Property<int?>("MinHoursMonth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("min_hours_month");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("schedule_id");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ScheduleId", "EmployeeId")
                        .IsUnique();

                    b.ToTable("schedule_employee");
                });

            modelBuilder.Entity("DataAccessLayer.Models.ScheduleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT")
                        .HasColumnName("comment");

                    b.Property<int>("ContainerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("container_id");

                    b.Property<int>("MaxConsecutiveDays")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_consecutive_days");

                    b.Property<int>("MaxConsecutiveFull")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_consecutive_full");

                    b.Property<int>("MaxFullPerMonth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_full_per_month");

                    b.Property<int>("MaxHoursPerEmpMonth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_hours_per_emp_month");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER")
                        .HasColumnName("month");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("PeoplePerShift")
                        .HasColumnType("INTEGER")
                        .HasColumnName("people_per_shift");

                    b.Property<string>("Shift1Time")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("shift1_time");

                    b.Property<string>("Shift2Time")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("shift2_time");

                    b.Property<int>("ShopId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("shop_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("ContainerId")
                        .HasDatabaseName("ix_sched_container");

                    b.HasIndex("ContainerId", "ShopId")
                        .HasDatabaseName("ix_sched_container_shop");

                    b.HasIndex("ShopId", "Year", "Month")
                        .HasDatabaseName("ix_sched_shop_month");

                    b.HasIndex(new[] { "ContainerId" }, "ix_sched_container");

                    b.HasIndex(new[] { "ContainerId", "ShopId" }, "ix_sched_container_shop");

                    b.HasIndex(new[] { "ShopId", "Year", "Month" }, "ix_sched_shop_month");

                    b.ToTable("schedule", t =>
                        {
                            t.HasCheckConstraint("ck_schedule_max_consecutive_days", "max_consecutive_days >= 1");

                            t.HasCheckConstraint("ck_schedule_max_consecutive_full", "max_consecutive_full >= 1");

                            t.HasCheckConstraint("ck_schedule_max_full_per_month", "max_full_per_month >= 0");

                            t.HasCheckConstraint("ck_schedule_max_hours_per_emp_month", "max_hours_per_emp_month >= 0");

                            t.HasCheckConstraint("ck_schedule_month", "month BETWEEN 1 AND 12");

                            t.HasCheckConstraint("ck_schedule_people_per_shift", "people_per_shift >= 1");

                            t.HasCheckConstraint("ck_schedule_shift1_format", "shift1_time LIKE '__:__ - __:__'");

                            t.HasCheckConstraint("ck_schedule_shift2_format", "shift2_time LIKE '__:__ - __:__'");
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.ScheduleSlotModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("DayOfMonth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("day_of_month");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("employee_id");

                    b.Property<string>("FromTime")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("from_time");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("schedule_id");

                    b.Property<int?>("ShiftNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("shift_no");

                    b.Property<int>("SlotNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("slot_no");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("UNFURNISHED")
                        .HasColumnName("status");

                    b.Property<string>("ToTime")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("to_time");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ScheduleId", "DayOfMonth", "FromTime", "ToTime", "EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("ux_slot_unique_emp_per_time")
                        .HasFilter("employee_id IS NOT NULL");

                    b.HasIndex("ScheduleId", "DayOfMonth", "FromTime", "ToTime", "SlotNo")
                        .IsUnique();

                    b.HasIndex(new[] { "ScheduleId", "DayOfMonth", "FromTime", "ToTime", "EmployeeId" }, "ux_slot_unique_emp_per_time")
                        .IsUnique()
                        .HasDatabaseName("ux_slot_unique_emp_per_time1");

                    b.ToTable("schedule_slot", t =>
                        {
                            t.HasCheckConstraint("ck_schedule_slot_dom", "day_of_month BETWEEN 1 AND 31");

                            t.HasCheckConstraint("ck_schedule_slot_slot_no", "slot_no >= 1");

                            t.HasCheckConstraint("ck_schedule_slot_status_pair", "((status='UNFURNISHED' AND employee_id IS NULL) OR (status='ASSIGNED' AND employee_id IS NOT NULL))");

                            t.HasCheckConstraint("ck_schedule_slot_time_format", "from_time LIKE '__:__' AND to_time LIKE '__:__'");

                            t.HasCheckConstraint("ck_schedule_slot_time_order", "from_time < to_time");
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.ShopModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("shop");
                });

            modelBuilder.Entity("DataAccessLayer.Models.AvailabilityDayModel", b =>
                {
                    b.HasOne("DataAccessLayer.Models.AvailabilityMonthModel", "AvailabilityMonth")
                        .WithMany("Days")
                        .HasForeignKey("AvailabilityMonthId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AvailabilityMonth");
                });

            modelBuilder.Entity("DataAccessLayer.Models.AvailabilityMonthModel", b =>
                {
                    b.HasOne("DataAccessLayer.Models.EmployeeModel", "Employee")
                        .WithMany("AvailabilityMonths")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("DataAccessLayer.Models.ScheduleEmployeeModel", b =>
                {
                    b.HasOne("DataAccessLayer.Models.EmployeeModel", "Employee")
                        .WithMany("ScheduleEmployees")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.ScheduleModel", "Schedule")
                        .WithMany("Employees")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("DataAccessLayer.Models.ScheduleModel", b =>
                {
                    b.HasOne("DataAccessLayer.Models.ContainerModel", "Container")
                        .WithMany("Schedules")
                        .HasForeignKey("ContainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.ShopModel", "Shop")
                        .WithMany("Schedules")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Container");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("DataAccessLayer.Models.ScheduleSlotModel", b =>
                {
                    b.HasOne("DataAccessLayer.Models.EmployeeModel", "Employee")
                        .WithMany("ScheduleSlots")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DataAccessLayer.Models.ScheduleModel", "Schedule")
                        .WithMany("Slots")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("DataAccessLayer.Models.AvailabilityMonthModel", b =>
                {
                    b.Navigation("Days");
                });

            modelBuilder.Entity("DataAccessLayer.Models.ContainerModel", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("DataAccessLayer.Models.EmployeeModel", b =>
                {
                    b.Navigation("AvailabilityMonths");

                    b.Navigation("ScheduleEmployees");

                    b.Navigation("ScheduleSlots");
                });

            modelBuilder.Entity("DataAccessLayer.Models.ScheduleModel", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("Slots");
                });

            modelBuilder.Entity("DataAccessLayer.Models.ShopModel", b =>
                {
                    b.Navigation("Schedules");
                });
#pragma warning restore 612, 618
        }
    }
}
