// <auto-generated />
using System;
using DataAccessLayer.Models.DataBaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260625182917_AddCommunicationVisibilityWindow")]
    partial class AddCommunicationVisibilityWindow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("DataAccessLayer.Models.AvailabilityGroupDayModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("AvailabilityGroupMemberId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("availability_group_member_id");

                    b.Property<int>("DayOfMonth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("day_of_month");

                    b.Property<string>("IntervalStr")
                        .HasColumnType("TEXT")
                        .HasColumnName("interval_str");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.HasKey("Id");

                    b.HasIndex("AvailabilityGroupMemberId", "DayOfMonth")
                        .IsUnique()
                        .HasDatabaseName("ux_avail_group_day_member_dom");

                    b.HasIndex(new[] { "AvailabilityGroupMemberId", "DayOfMonth" }, "ux_avail_group_day_member_dom")
                        .IsUnique();

                    b.ToTable("availability_group_day", t =>
                        {
                            t.HasCheckConstraint("ck_avail_group_day_dom", "day_of_month BETWEEN 1 AND 31");

                            t.HasCheckConstraint("ck_avail_group_day_kind_interval", "((kind = 'INT' AND interval_str IS NOT NULL AND length(trim(interval_str)) >= 11) OR (kind = 'ANY' AND interval_str IS NULL) OR kind = 'NONE')");
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.AvailabilityGroupMemberModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("AvailabilityGroupId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("availability_group_id");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("employee_id");

                    b.Property<DateTimeOffset?>("EmployeeLastModifiedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("employee_last_modified_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("AvailabilityGroupId", "EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("ux_avail_group_member_group_emp");

                    b.HasIndex(new[] { "AvailabilityGroupId", "EmployeeId" }, "ux_avail_group_member_group_emp")
                        .IsUnique();

                    b.ToTable("availability_group_member");
                });

            modelBuilder.Entity("DataAccessLayer.Models.AvailabilityGroupModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER")
                        .HasColumnName("month");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("PublicationStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Private")
                        .HasColumnName("publication_status");

                    b.Property<DateTimeOffset?>("VisibleFromUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("visible_from_utc");

                    b.Property<DateTimeOffset?>("VisibleToUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("visible_to_utc");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("PublicationStatus", "VisibleFromUtc", "VisibleToUtc")
                        .HasDatabaseName("ix_avail_group_publication_visibility");

                    b.HasIndex("Year", "Month", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_avail_group_year_month_name");

                    b.HasIndex(new[] { "Year", "Month", "Name" }, "ix_avail_group_year_month_name");

                    b.ToTable("availability_group", t =>
                        {
                            t.HasCheckConstraint("ck_availability_group_month", "month BETWEEN 1 AND 12");
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.BindModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("AvailabilityBinds");
                });

            modelBuilder.Entity("DataAccessLayer.Models.CommunicationMessageModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<int?>("CreatedByManagerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_by_manager_id");

                    b.Property<string>("CreatedByManagerName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_manager_name");

                    b.Property<DateTimeOffset>("DeadlineAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("deadline_at_utc");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("VisibleFromUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("visible_from_utc");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_communication_message_created");

                    b.HasIndex("CreatedByManagerId");

                    b.HasIndex("DeadlineAtUtc")
                        .HasDatabaseName("ix_communication_message_deadline");

                    b.HasIndex("VisibleFromUtc")
                        .HasDatabaseName("ix_communication_message_visible_from");

                    b.ToTable("communication_message", t =>
                        {
                            t.HasCheckConstraint("ck_communication_message_body", "length(trim(body)) > 0");

                            t.HasCheckConstraint("ck_communication_message_deadline", "deadline_at_utc > created_at_utc");

                            t.HasCheckConstraint("ck_communication_message_title", "length(trim(title)) > 0");
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.ContainerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("container");
                });

            modelBuilder.Entity("DataAccessLayer.Models.EmployeeAccountModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("employee_id");

                    b.Property<DateTimeOffset?>("LastLoginAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_login_at_utc");

                    b.Property<DateTimeOffset?>("LastSeenAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_seen_at_utc");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordResetCodeHash")
                        .HasColumnType("TEXT")
                        .HasColumnName("password_reset_code_hash");

                    b.Property<DateTimeOffset?>("PasswordResetExpiresAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("password_reset_expires_at_utc");

                    b.Property<DateTimeOffset?>("PasswordResetRequestedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("password_reset_requested_at_utc");

                    b.Property<DateTimeOffset>("PasswordUpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("password_updated_at_utc");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("username")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("ux_employee_account_employee");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ux_employee_account_username");

                    b.ToTable("employee_account");
                });

            modelBuilder.Entity("DataAccessLayer.Models.EmployeeCommunicationDismissalModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("CommunicationMessageId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("communication_message_id");

                    b.Property<DateTimeOffset>("DismissedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("dismissed_at_utc");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("employee_id");

                    b.HasKey("Id");

                    b.HasIndex("CommunicationMessageId", "EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("ux_employee_comm_dismissal_msg_emp");

                    b.HasIndex("EmployeeId", "DismissedAtUtc")
                        .HasDatabaseName("ix_employee_comm_dismissal_emp_time");

                    b.ToTable("employee_communication_dismissal");
                });

            modelBuilder.Entity("DataAccessLayer.Models.EmployeeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_name");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.HasKey("Id");

                    b.HasIndex("FirstName", "LastName")
                        .IsUnique()
                        .HasDatabaseName("ux_employee_full_name");

                    b.ToTable("employee");
                });

            modelBuilder.Entity("DataAccessLayer.Models.ManagerAccountModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<DateTimeOffset?>("LastLoginAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_login_at_utc");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordResetCodeHash")
                        .HasColumnType("TEXT")
                        .HasColumnName("password_reset_code_hash");

                    b.Property<DateTimeOffset?>("PasswordResetExpiresAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("password_reset_expires_at_utc");

                    b.Property<DateTimeOffset?>("PasswordResetRequestedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("password_reset_requested_at_utc");

                    b.Property<DateTimeOffset>("PasswordUpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("password_updated_at_utc");

                    b.Property<string>("RecoveryEmail")
                        .HasMaxLength(254)
                        .HasColumnType("TEXT")
                        .HasColumnName("recovery_email");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("username")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ux_manager_account_username");

                    b.ToTable("manager_account");
                });

            modelBuilder.Entity("DataAccessLayer.Models.ScheduleCellStyleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("BackgroundColorArgb")
                        .HasColumnType("INTEGER")
                        .HasColumnName("background_color_argb");

                    b.Property<int>("DayOfMonth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("day_of_month");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("employee_id");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("schedule_id");

                    b.Property<int?>("TextColorArgb")
                        .HasColumnType("INTEGER")
                        .HasColumnName("text_color_argb");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ScheduleId", "DayOfMonth", "EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("ux_sched_cell_style");

                    b.ToTable("schedule_cell_style", t =>
                        {
                            t.HasCheckConstraint("ck_schedule_cell_style_dom", "day_of_month BETWEEN 1 AND 31");
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.ScheduleEmployeeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("employee_id");

                    b.Property<int?>("MinHoursMonth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("min_hours_month");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("schedule_id");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ScheduleId", "EmployeeId")
                        .IsUnique();

                    b.ToTable("schedule_employee");
                });

            modelBuilder.Entity("DataAccessLayer.Models.ScheduleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("AvailabilityGroupId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("availability_group_id");

                    b.Property<int>("ContainerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("container_id");

                    b.Property<int>("MaxConsecutiveDays")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_consecutive_days");

                    b.Property<int>("MaxConsecutiveFull")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_consecutive_full");

                    b.Property<int>("MaxFullPerMonth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_full_per_month");

                    b.Property<int>("MaxHoursPerEmpMonth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_hours_per_emp_month");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER")
                        .HasColumnName("month");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.Property<int>("PeoplePerShift")
                        .HasColumnType("INTEGER")
                        .HasColumnName("people_per_shift");

                    b.Property<string>("PublicationStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Private")
                        .HasColumnName("publication_status");

                    b.Property<string>("Shift1Time")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("shift1_time");

                    b.Property<string>("Shift2Time")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("shift2_time");

                    b.Property<int>("ShopId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("shop_id");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("AvailabilityGroupId")
                        .HasDatabaseName("ix_sched_avail_group");

                    b.HasIndex("ContainerId")
                        .HasDatabaseName("ix_sched_container");

                    b.HasIndex("PublicationStatus")
                        .HasDatabaseName("ix_sched_publication_status");

                    b.HasIndex("ContainerId", "ShopId")
                        .HasDatabaseName("ix_sched_container_shop");

                    b.HasIndex("ShopId", "Year", "Month")
                        .HasDatabaseName("ix_sched_shop_month");

                    b.HasIndex(new[] { "ContainerId" }, "ix_sched_container");

                    b.HasIndex(new[] { "ContainerId", "ShopId" }, "ix_sched_container_shop");

                    b.HasIndex(new[] { "ShopId", "Year", "Month" }, "ix_sched_shop_month");

                    b.ToTable("schedule", t =>
                        {
                            t.HasCheckConstraint("ck_schedule_max_consecutive_days", "max_consecutive_days >= 1");

                            t.HasCheckConstraint("ck_schedule_max_consecutive_full", "max_consecutive_full >= 1");

                            t.HasCheckConstraint("ck_schedule_max_full_per_month", "max_full_per_month >= 0");

                            t.HasCheckConstraint("ck_schedule_max_hours_per_emp_month", "max_hours_per_emp_month >= 0");

                            t.HasCheckConstraint("ck_schedule_month", "month BETWEEN 1 AND 12");

                            t.HasCheckConstraint("ck_schedule_people_per_shift", "people_per_shift >= 1");

                            t.HasCheckConstraint("ck_schedule_shift1_format", "shift1_time LIKE '__:__ - __:__'");

                            t.HasCheckConstraint("ck_schedule_shift2_format", "shift2_time LIKE '__:__ - __:__'");
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.SchedulePresetEmployeeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("employee_id");

                    b.Property<int>("MinHoursMonth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("min_hours_month");

                    b.Property<int>("SchedulePresetId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("schedule_preset_id");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_schedule_preset_employee_employee");

                    b.HasIndex("SchedulePresetId", "EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("ux_schedule_preset_employee");

                    b.ToTable("schedule_preset_employee", t =>
                        {
                            t.HasCheckConstraint("ck_schedule_preset_employee_min_hours", "min_hours_month >= 0");
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.SchedulePresetModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("AvailabilityGroupId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("availability_group_id");

                    b.Property<int>("ContainerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("container_id");

                    b.Property<int>("MaxConsecutiveDays")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_consecutive_days");

                    b.Property<int>("MaxConsecutiveFull")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_consecutive_full");

                    b.Property<int>("MaxFullPerMonth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_full_per_month");

                    b.Property<int>("MaxHoursPerEmpMonth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_hours_per_emp_month");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER")
                        .HasColumnName("month");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("PeoplePerShift")
                        .HasColumnType("INTEGER")
                        .HasColumnName("people_per_shift");

                    b.Property<string>("ScheduleName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("schedule_name");

                    b.Property<string>("Shift1Time")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("shift1_time");

                    b.Property<string>("Shift2Time")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("shift2_time");

                    b.Property<int>("ShopId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("shop_id");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("AvailabilityGroupId")
                        .HasDatabaseName("ix_schedule_preset_avail_group");

                    b.HasIndex("ContainerId")
                        .HasDatabaseName("ix_schedule_preset_container");

                    b.HasIndex("ShopId")
                        .HasDatabaseName("ix_schedule_preset_shop");

                    b.HasIndex("ContainerId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_schedule_preset_container_name");

                    b.ToTable("schedule_preset", t =>
                        {
                            t.HasCheckConstraint("ck_schedule_preset_max_consecutive_days", "max_consecutive_days >= 1");

                            t.HasCheckConstraint("ck_schedule_preset_max_consecutive_full", "max_consecutive_full >= 1");

                            t.HasCheckConstraint("ck_schedule_preset_max_full_per_month", "max_full_per_month >= 1");

                            t.HasCheckConstraint("ck_schedule_preset_max_hours_per_emp_month", "max_hours_per_emp_month >= 1");

                            t.HasCheckConstraint("ck_schedule_preset_month", "month BETWEEN 1 AND 12");

                            t.HasCheckConstraint("ck_schedule_preset_people_per_shift", "people_per_shift >= 1");

                            t.HasCheckConstraint("ck_schedule_preset_shift1_format", "shift1_time LIKE '__:__ - __:__'");

                            t.HasCheckConstraint("ck_schedule_preset_shift2_format", "shift2_time LIKE '__:__ - __:__'");
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.ScheduleSlotModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("DayOfMonth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("day_of_month");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("employee_id");

                    b.Property<string>("FromTime")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("from_time");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("schedule_id");

                    b.Property<int>("SlotNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("slot_no");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("UNFURNISHED")
                        .HasColumnName("status");

                    b.Property<string>("ToTime")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("to_time");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ScheduleId", "DayOfMonth", "FromTime", "ToTime", "EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("ux_slot_unique_emp_per_time")
                        .HasFilter("employee_id IS NOT NULL");

                    b.HasIndex("ScheduleId", "DayOfMonth", "FromTime", "ToTime", "SlotNo")
                        .IsUnique();

                    b.ToTable("schedule_slot", t =>
                        {
                            t.HasCheckConstraint("ck_schedule_slot_dom", "day_of_month BETWEEN 1 AND 31");

                            t.HasCheckConstraint("ck_schedule_slot_slot_no", "slot_no >= 1");

                            t.HasCheckConstraint("ck_schedule_slot_status_pair", "((status='UNFURNISHED' AND employee_id IS NULL) OR (status='ASSIGNED' AND employee_id IS NOT NULL))");

                            t.HasCheckConstraint("ck_schedule_slot_time_format", "from_time LIKE '__:__' AND to_time LIKE '__:__'");

                            t.HasCheckConstraint("ck_schedule_slot_time_order", "from_time < to_time");
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.ShiftSwapRequestModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("accepted_at_utc");

                    b.Property<int?>("AcceptedByEmployeeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("accepted_by_employee_id");

                    b.Property<DateTimeOffset?>("CancelledAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("cancelled_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<int?>("FromEmployeeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("from_employee_id");

                    b.Property<bool>("IsManagerCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_manager_created");

                    b.Property<int?>("ManualColumnId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("manual_column_id");

                    b.Property<string>("OfferedFromTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("offered_from_time");

                    b.Property<string>("OfferedToTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("offered_to_time");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("schedule_id");

                    b.Property<int>("ScheduleSlotId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("schedule_slot_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Open")
                        .HasColumnName("status");

                    b.Property<int?>("TargetEmployeeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("target_employee_id");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Public")
                        .HasColumnName("visibility");

                    b.HasKey("Id");

                    b.HasIndex("AcceptedByEmployeeId");

                    b.HasIndex("ScheduleSlotId", "Status")
                        .IsUnique()
                        .HasDatabaseName("ux_shift_swap_open_slot")
                        .HasFilter("status = 'Open'");

                    b.HasIndex(new[] { "FromEmployeeId", "Status" }, "ix_shift_swap_from_status");

                    b.HasIndex(new[] { "ScheduleId", "Status" }, "ix_shift_swap_schedule_status");

                    b.HasIndex(new[] { "TargetEmployeeId", "Status" }, "ix_shift_swap_target_status");

                    b.ToTable("shift_swap_request");
                });

            modelBuilder.Entity("DataAccessLayer.Models.ShopModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("address");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_shop_name");

                    b.ToTable("shop");
                });

            modelBuilder.Entity("DataAccessLayer.Models.WorkflowLogEntryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("action");

                    b.Property<int?>("ActorEmployeeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("actor_employee_id");

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("actor_name");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("actor_role");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("occurred_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("ix_workflow_log_occurred_at");

                    b.HasIndex("ActorRole", "OccurredAtUtc")
                        .HasDatabaseName("ix_workflow_log_role_time");

                    b.HasIndex(new[] { "OccurredAtUtc" }, "ix_workflow_log_occurred_at");

                    b.HasIndex(new[] { "ActorRole", "OccurredAtUtc" }, "ix_workflow_log_role_time");

                    b.ToTable("workflow_log_entry");
                });

            modelBuilder.Entity("DataAccessLayer.Models.AvailabilityGroupDayModel", b =>
                {
                    b.HasOne("DataAccessLayer.Models.AvailabilityGroupMemberModel", "AvailabilityGroupMember")
                        .WithMany("Days")
                        .HasForeignKey("AvailabilityGroupMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AvailabilityGroupMember");
                });

            modelBuilder.Entity("DataAccessLayer.Models.AvailabilityGroupMemberModel", b =>
                {
                    b.HasOne("DataAccessLayer.Models.AvailabilityGroupModel", "AvailabilityGroup")
                        .WithMany("Members")
                        .HasForeignKey("AvailabilityGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.EmployeeModel", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AvailabilityGroup");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("DataAccessLayer.Models.CommunicationMessageModel", b =>
                {
                    b.HasOne("DataAccessLayer.Models.ManagerAccountModel", "CreatedByManager")
                        .WithMany()
                        .HasForeignKey("CreatedByManagerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByManager");
                });

            modelBuilder.Entity("DataAccessLayer.Models.EmployeeAccountModel", b =>
                {
                    b.HasOne("DataAccessLayer.Models.EmployeeModel", "Employee")
                        .WithOne("Account")
                        .HasForeignKey("DataAccessLayer.Models.EmployeeAccountModel", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("DataAccessLayer.Models.EmployeeCommunicationDismissalModel", b =>
                {
                    b.HasOne("DataAccessLayer.Models.CommunicationMessageModel", "CommunicationMessage")
                        .WithMany("Dismissals")
                        .HasForeignKey("CommunicationMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.EmployeeModel", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommunicationMessage");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("DataAccessLayer.Models.ScheduleCellStyleModel", b =>
                {
                    b.HasOne("DataAccessLayer.Models.EmployeeModel", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.ScheduleModel", "Schedule")
                        .WithMany("CellStyles")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("DataAccessLayer.Models.ScheduleEmployeeModel", b =>
                {
                    b.HasOne("DataAccessLayer.Models.EmployeeModel", "Employee")
                        .WithMany("ScheduleEmployees")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.ScheduleModel", "Schedule")
                        .WithMany("Employees")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("DataAccessLayer.Models.ScheduleModel", b =>
                {
                    b.HasOne("DataAccessLayer.Models.AvailabilityGroupModel", "AvailabilityGroup")
                        .WithMany()
                        .HasForeignKey("AvailabilityGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DataAccessLayer.Models.ContainerModel", "Container")
                        .WithMany("Schedules")
                        .HasForeignKey("ContainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.ShopModel", "Shop")
                        .WithMany("Schedules")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AvailabilityGroup");

                    b.Navigation("Container");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("DataAccessLayer.Models.SchedulePresetEmployeeModel", b =>
                {
                    b.HasOne("DataAccessLayer.Models.EmployeeModel", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.SchedulePresetModel", "SchedulePreset")
                        .WithMany("Employees")
                        .HasForeignKey("SchedulePresetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchedulePreset");
                });

            modelBuilder.Entity("DataAccessLayer.Models.SchedulePresetModel", b =>
                {
                    b.HasOne("DataAccessLayer.Models.AvailabilityGroupModel", null)
                        .WithMany()
                        .HasForeignKey("AvailabilityGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DataAccessLayer.Models.ContainerModel", null)
                        .WithMany()
                        .HasForeignKey("ContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.ShopModel", null)
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccessLayer.Models.ScheduleSlotModel", b =>
                {
                    b.HasOne("DataAccessLayer.Models.EmployeeModel", "Employee")
                        .WithMany("ScheduleSlots")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DataAccessLayer.Models.ScheduleModel", "Schedule")
                        .WithMany("Slots")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("DataAccessLayer.Models.ShiftSwapRequestModel", b =>
                {
                    b.HasOne("DataAccessLayer.Models.EmployeeModel", "AcceptedByEmployee")
                        .WithMany()
                        .HasForeignKey("AcceptedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DataAccessLayer.Models.EmployeeModel", "FromEmployee")
                        .WithMany()
                        .HasForeignKey("FromEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DataAccessLayer.Models.ScheduleModel", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.ScheduleSlotModel", "ScheduleSlot")
                        .WithMany()
                        .HasForeignKey("ScheduleSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.EmployeeModel", "TargetEmployee")
                        .WithMany()
                        .HasForeignKey("TargetEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AcceptedByEmployee");

                    b.Navigation("FromEmployee");

                    b.Navigation("Schedule");

                    b.Navigation("ScheduleSlot");

                    b.Navigation("TargetEmployee");
                });

            modelBuilder.Entity("DataAccessLayer.Models.AvailabilityGroupMemberModel", b =>
                {
                    b.Navigation("Days");
                });

            modelBuilder.Entity("DataAccessLayer.Models.AvailabilityGroupModel", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("DataAccessLayer.Models.CommunicationMessageModel", b =>
                {
                    b.Navigation("Dismissals");
                });

            modelBuilder.Entity("DataAccessLayer.Models.ContainerModel", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("DataAccessLayer.Models.EmployeeModel", b =>
                {
                    b.Navigation("Account");

                    b.Navigation("ScheduleEmployees");

                    b.Navigation("ScheduleSlots");
                });

            modelBuilder.Entity("DataAccessLayer.Models.ScheduleModel", b =>
                {
                    b.Navigation("CellStyles");

                    b.Navigation("Employees");

                    b.Navigation("Slots");
                });

            modelBuilder.Entity("DataAccessLayer.Models.SchedulePresetModel", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("DataAccessLayer.Models.ShopModel", b =>
                {
                    b.Navigation("Schedules");
                });
#pragma warning restore 612, 618
        }
    }
}
