// <auto-generated />
using System;
using DataAccessLayer.Models.DataBaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260809120532_AddManagerGraphFillColorBinds")]
    partial class AddManagerGraphFillColorBinds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("DataAccessLayer.Models.AvailabilityGroupDayModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("AvailabilityGroupMemberId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("availability_group_member_id");

                    b.Property<int>("DayOfMonth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("day_of_month");

                    b.Property<string>("IntervalStr")
                        .HasColumnType("TEXT")
                        .HasColumnName("interval_str");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("kind");

                    b.HasKey("Id");

                    b.HasIndex("AvailabilityGroupMemberId", "DayOfMonth")
                        .IsUnique()
                        .HasDatabaseName("ux_avail_group_day_member_dom");

                    b.HasIndex(new[] { "AvailabilityGroupMemberId", "DayOfMonth" }, "ux_avail_group_day_member_dom")
                        .IsUnique();

                    b.ToTable("availability_group_day", t =>
                        {
                            t.HasCheckConstraint("ck_avail_group_day_dom", "day_of_month BETWEEN 1 AND 31");

                            t.HasCheckConstraint("ck_avail_group_day_kind_interval", "((kind = 'INT' AND interval_str IS NOT NULL AND length(trim(interval_str)) >= 11) OR (kind = 'ANY' AND interval_str IS NULL) OR kind = 'NONE')");
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.AvailabilityGroupDayTransferModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("DayOfMonth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("day_of_month");

                    b.Property<int>("SourceMemberId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("source_member_id");

                    b.Property<int>("TargetMemberId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("target_member_id");

                    b.HasKey("Id");

                    b.HasIndex("SourceMemberId", "DayOfMonth")
                        .IsUnique()
                        .HasDatabaseName("ux_avail_transfer_source_day");

                    b.HasIndex("TargetMemberId", "DayOfMonth")
                        .IsUnique()
                        .HasDatabaseName("ux_avail_transfer_target_day");

                    b.HasIndex(new[] { "SourceMemberId", "DayOfMonth" }, "ux_avail_transfer_source_day")
                        .IsUnique();

                    b.HasIndex(new[] { "TargetMemberId", "DayOfMonth" }, "ux_avail_transfer_target_day")
                        .IsUnique();

                    b.ToTable("availability_group_day_transfer", t =>
                        {
                            t.HasCheckConstraint("ck_avail_transfer_distinct_members", "source_member_id <> target_member_id");

                            t.HasCheckConstraint("ck_avail_transfer_dom", "day_of_month BETWEEN 1 AND 31");
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.AvailabilityGroupMemberModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("AvailabilityGroupId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("availability_group_id");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("employee_id");

                    b.Property<DateTimeOffset?>("EmployeeLastModifiedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("employee_last_modified_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("AvailabilityGroupId", "EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("ux_avail_group_member_group_emp");

                    b.HasIndex(new[] { "AvailabilityGroupId", "EmployeeId" }, "ux_avail_group_member_group_emp")
                        .IsUnique();

                    b.ToTable("availability_group_member");
                });

            modelBuilder.Entity("DataAccessLayer.Models.AvailabilityGroupModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER")
                        .HasColumnName("month");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("PublicationStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Private")
                        .HasColumnName("publication_status");

                    b.Property<DateTimeOffset?>("VisibleFromUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("visible_from_utc");

                    b.Property<DateTimeOffset?>("VisibleToUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("visible_to_utc");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("PublicationStatus", "VisibleFromUtc", "VisibleToUtc")
                        .HasDatabaseName("ix_avail_group_publication_visibility");

                    b.HasIndex("Year", "Month", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_avail_group_year_month_name");

                    b.HasIndex(new[] { "Year", "Month", "Name" }, "ix_avail_group_year_month_name");

                    b.ToTable("availability_group", t =>
                        {
                            t.HasCheckConstraint("ck_availability_group_month", "month BETWEEN 1 AND 12");
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.BindModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ManagerAccountId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ManagerAccountId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ux_availability_bind_manager_key");

                    b.ToTable("AvailabilityBinds");
                });

            modelBuilder.Entity("DataAccessLayer.Models.CommunicationMessageModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<int?>("CreatedByManagerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_by_manager_id");

                    b.Property<string>("CreatedByManagerName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_manager_name");

                    b.Property<DateTimeOffset>("DeadlineAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("deadline_at_utc");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset?>("VisibleFromUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("visible_from_utc");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_communication_message_created");

                    b.HasIndex("CreatedByManagerId");

                    b.HasIndex("DeadlineAtUtc")
                        .HasDatabaseName("ix_communication_message_deadline");

                    b.HasIndex("VisibleFromUtc")
                        .HasDatabaseName("ix_communication_message_visible_from");

                    b.ToTable("communication_message", t =>
                        {
                            t.HasCheckConstraint("ck_communication_message_body", "length(trim(body)) > 0");

                            t.HasCheckConstraint("ck_communication_message_deadline", "deadline_at_utc > created_at_utc");

                            t.HasCheckConstraint("ck_communication_message_title", "length(trim(title)) > 0");
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.ContainerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("container");
                });

            modelBuilder.Entity("DataAccessLayer.Models.EmployeeAccountModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("employee_id");

                    b.Property<DateTimeOffset?>("LastLoginAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_login_at_utc");

                    b.Property<DateTimeOffset?>("LastSeenAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_seen_at_utc");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordResetCodeHash")
                        .HasColumnType("TEXT")
                        .HasColumnName("password_reset_code_hash");

                    b.Property<DateTimeOffset?>("PasswordResetExpiresAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("password_reset_expires_at_utc");

                    b.Property<DateTimeOffset?>("PasswordResetRequestedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("password_reset_requested_at_utc");

                    b.Property<DateTimeOffset>("PasswordUpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("password_updated_at_utc");

                    b.Property<int>("SessionVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("session_version");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("username")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("ux_employee_account_employee");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ux_employee_account_username");

                    b.ToTable("employee_account");
                });

            modelBuilder.Entity("DataAccessLayer.Models.EmployeeCommunicationDismissalModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("CommunicationMessageId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("communication_message_id");

                    b.Property<DateTimeOffset>("DismissedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("dismissed_at_utc");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("employee_id");

                    b.HasKey("Id");

                    b.HasIndex("CommunicationMessageId", "EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("ux_employee_comm_dismissal_msg_emp");

                    b.HasIndex("EmployeeId", "DismissedAtUtc")
                        .HasDatabaseName("ix_employee_comm_dismissal_emp_time");

                    b.ToTable("employee_communication_dismissal");
                });

            modelBuilder.Entity("DataAccessLayer.Models.EmployeeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("last_name");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT")
                        .HasColumnName("phone");

                    b.HasKey("Id");

                    b.HasIndex("FirstName", "LastName")
                        .IsUnique()
                        .HasDatabaseName("ux_employee_full_name");

                    b.ToTable("employee");
                });

            modelBuilder.Entity("DataAccessLayer.Models.EmployeeNotificationReadModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("employee_id");

                    b.Property<string>("NotificationId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT")
                        .HasColumnName("notification_id");

                    b.Property<DateTimeOffset>("ReadAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("read_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "NotificationId")
                        .IsUnique()
                        .HasDatabaseName("ux_emp_notification_read_emp_notification");

                    b.HasIndex("EmployeeId", "ReadAtUtc")
                        .HasDatabaseName("ix_emp_notification_read_emp_time");

                    b.ToTable("employee_notification_read");
                });

            modelBuilder.Entity("DataAccessLayer.Models.EmployeePinnedSwapModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("employee_id");

                    b.Property<DateTimeOffset>("PinnedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("pinned_at_utc");

                    b.Property<int>("ShiftSwapId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("shift_swap_id");

                    b.HasKey("Id");

                    b.HasIndex("ShiftSwapId");

                    b.HasIndex("EmployeeId", "PinnedAtUtc")
                        .HasDatabaseName("ix_employee_pinned_swap_employee_time");

                    b.HasIndex("EmployeeId", "ShiftSwapId")
                        .IsUnique()
                        .HasDatabaseName("ux_employee_pinned_swap_employee_swap");

                    b.ToTable("employee_pinned_swap");
                });

            modelBuilder.Entity("DataAccessLayer.Models.EmployeeScheduleColumnPreferenceModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("ColumnOrderJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("column_order_json");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("employee_id");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("schedule_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("ScheduleId");

                    b.HasIndex("EmployeeId", "ScheduleId")
                        .IsUnique()
                        .HasDatabaseName("ux_emp_schedule_column_pref_emp_schedule");

                    b.ToTable("employee_schedule_column_preference");
                });

            modelBuilder.Entity("DataAccessLayer.Models.ManagerAccountModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_system");

                    b.Property<DateTimeOffset?>("LastLoginAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_login_at_utc");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordResetCodeHash")
                        .HasColumnType("TEXT")
                        .HasColumnName("password_reset_code_hash");

                    b.Property<DateTimeOffset?>("PasswordResetExpiresAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("password_reset_expires_at_utc");

                    b.Property<DateTimeOffset?>("PasswordResetRequestedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("password_reset_requested_at_utc");

                    b.Property<DateTimeOffset>("PasswordUpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("password_updated_at_utc");

                    b.Property<string>("RecoveryEmail")
                        .HasMaxLength(254)
                        .HasColumnType("TEXT")
                        .HasColumnName("recovery_email");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("username")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("IsSystem")
                        .IsUnique()
                        .HasDatabaseName("ux_manager_account_system")
                        .HasFilter("\"is_system\" = 1");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ux_manager_account_username");

                    b.ToTable("manager_account");
                });

            modelBuilder.Entity("DataAccessLayer.Models.ManagerGraphFillColorBindModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("FillColor")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT")
                        .HasColumnName("fill_color");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<int>("ManagerAccountId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("manager_account_id");

                    b.HasKey("Id");

                    b.HasIndex("ManagerAccountId", "FillColor")
                        .IsUnique()
                        .HasDatabaseName("ux_manager_graph_fill_bind_color");

                    b.HasIndex("ManagerAccountId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ux_manager_graph_fill_bind_key");

                    b.ToTable("manager_graph_fill_color_bind");
                });

            modelBuilder.Entity("DataAccessLayer.Models.ManagerNoteModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("color");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(20000)
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("ManagerAccountId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("manager_account_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("ManagerAccountId", "UpdatedAtUtc")
                        .HasDatabaseName("ix_manager_note_manager_updated");

                    b.ToTable("manager_note");
                });

            modelBuilder.Entity("DataAccessLayer.Models.ManagerNotepadStateModel", b =>
                {
                    b.Property<int>("ManagerAccountId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("manager_account_id");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER")
                        .HasColumnName("height");

                    b.Property<bool>("IsExpanded")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_expanded");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_pinned");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("ManagerAccountId");

                    b.ToTable("manager_notepad_state");
                });

            modelBuilder.Entity("DataAccessLayer.Models.RegulationAcceptanceModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AcceptedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("accepted_at_utc");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("account_id");

                    b.Property<string>("AccountRole")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("account_role");

                    b.Property<string>("DisplayNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("display_name_snapshot");

                    b.Property<int>("RegulationDocumentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("regulation_document_id");

                    b.Property<string>("UsernameSnapshot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("username_snapshot");

                    b.HasKey("Id");

                    b.HasIndex("AccountRole", "AccountId", "AcceptedAtUtc")
                        .HasDatabaseName("ix_regulation_acceptance_subject_time");

                    b.HasIndex("RegulationDocumentId", "AccountRole", "AccountId")
                        .IsUnique()
                        .HasDatabaseName("ux_regulation_acceptance_subject");

                    b.ToTable("regulation_acceptance", t =>
                        {
                            t.HasCheckConstraint("ck_regulation_acceptance_role", "account_role IN ('manager', 'employee')");
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.RegulationDocumentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<int?>("CreatedByManagerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("created_by_manager_id");

                    b.Property<string>("CreatedByManagerName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_manager_name");

                    b.Property<bool>("IsPublished")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_published");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT")
                        .HasColumnName("message");

                    b.Property<byte[]>("PdfContent")
                        .IsRequired()
                        .HasColumnType("BLOB")
                        .HasColumnName("pdf_content");

                    b.Property<string>("PdfFileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT")
                        .HasColumnName("pdf_file_name");

                    b.Property<string>("PdfSha256")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("pdf_sha256");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("published_at_utc");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT")
                        .HasColumnName("version")
                        .UseCollation("NOCASE");

                    b.HasKey("Id");

                    b.HasIndex("Version")
                        .IsUnique()
                        .HasDatabaseName("ux_regulation_document_version");

                    b.HasIndex("IsPublished", "PublishedAtUtc")
                        .HasDatabaseName("ix_regulation_document_published");

                    b.ToTable("regulation_document");
                });

            modelBuilder.Entity("DataAccessLayer.Models.ScheduleCellStyleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("BackgroundColorArgb")
                        .HasColumnType("INTEGER")
                        .HasColumnName("background_color_argb");

                    b.Property<int>("DayOfMonth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("day_of_month");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("employee_id");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("schedule_id");

                    b.Property<int?>("TextColorArgb")
                        .HasColumnType("INTEGER")
                        .HasColumnName("text_color_argb");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ScheduleId", "DayOfMonth", "EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("ux_sched_cell_style");

                    b.ToTable("schedule_cell_style", t =>
                        {
                            t.HasCheckConstraint("ck_schedule_cell_style_dom", "day_of_month BETWEEN 1 AND 31");
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.ScheduleEmployeeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(0)
                        .HasColumnName("display_order");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("employee_id");

                    b.Property<int?>("MinHoursMonth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("min_hours_month");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("schedule_id");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ScheduleId", "EmployeeId")
                        .IsUnique();

                    b.ToTable("schedule_employee");
                });

            modelBuilder.Entity("DataAccessLayer.Models.ScheduleModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("AllowSwap")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("allow_swap");

                    b.Property<int?>("AvailabilityGroupId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("availability_group_id");

                    b.Property<int>("ContainerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("container_id");

                    b.Property<int>("MaxConsecutiveDays")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_consecutive_days");

                    b.Property<int>("MaxConsecutiveFull")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_consecutive_full");

                    b.Property<int>("MaxFullPerMonth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_full_per_month");

                    b.Property<int>("MaxHoursPerEmpMonth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_hours_per_emp_month");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER")
                        .HasColumnName("month");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.Property<int>("PeoplePerShift")
                        .HasColumnType("INTEGER")
                        .HasColumnName("people_per_shift");

                    b.Property<string>("PublicationStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Private")
                        .HasColumnName("publication_status");

                    b.Property<string>("Shift1Time")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("shift1_time");

                    b.Property<string>("Shift2Time")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("shift2_time");

                    b.Property<int>("ShopId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("shop_id");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("AvailabilityGroupId")
                        .HasDatabaseName("ix_sched_avail_group");

                    b.HasIndex("ContainerId")
                        .HasDatabaseName("ix_sched_container");

                    b.HasIndex("PublicationStatus")
                        .HasDatabaseName("ix_sched_publication_status");

                    b.HasIndex("ContainerId", "ShopId")
                        .HasDatabaseName("ix_sched_container_shop");

                    b.HasIndex("ShopId", "Year", "Month")
                        .HasDatabaseName("ix_sched_shop_month");

                    b.HasIndex(new[] { "ContainerId" }, "ix_sched_container");

                    b.HasIndex(new[] { "ContainerId", "ShopId" }, "ix_sched_container_shop");

                    b.HasIndex(new[] { "ShopId", "Year", "Month" }, "ix_sched_shop_month");

                    b.ToTable("schedule", t =>
                        {
                            t.HasCheckConstraint("ck_schedule_max_consecutive_days", "max_consecutive_days >= 1");

                            t.HasCheckConstraint("ck_schedule_max_consecutive_full", "max_consecutive_full >= 1");

                            t.HasCheckConstraint("ck_schedule_max_full_per_month", "max_full_per_month >= 0");

                            t.HasCheckConstraint("ck_schedule_max_hours_per_emp_month", "max_hours_per_emp_month >= 0");

                            t.HasCheckConstraint("ck_schedule_month", "month BETWEEN 1 AND 12");

                            t.HasCheckConstraint("ck_schedule_people_per_shift", "people_per_shift >= 1");

                            t.HasCheckConstraint("ck_schedule_shift1_format", "shift1_time LIKE '__:__ - __:__'");

                            t.HasCheckConstraint("ck_schedule_shift2_format", "shift2_time LIKE '__:__ - __:__'");
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.SchedulePresetEmployeeModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("employee_id");

                    b.Property<int>("MinHoursMonth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("min_hours_month");

                    b.Property<int>("SchedulePresetId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("schedule_preset_id");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .HasDatabaseName("ix_schedule_preset_employee_employee");

                    b.HasIndex("SchedulePresetId", "EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("ux_schedule_preset_employee");

                    b.ToTable("schedule_preset_employee", t =>
                        {
                            t.HasCheckConstraint("ck_schedule_preset_employee_min_hours", "min_hours_month >= 0");
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.SchedulePresetModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("AvailabilityGroupId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("availability_group_id");

                    b.Property<int>("ContainerId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("container_id");

                    b.Property<int>("MaxConsecutiveDays")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_consecutive_days");

                    b.Property<int>("MaxConsecutiveFull")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_consecutive_full");

                    b.Property<int>("MaxFullPerMonth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_full_per_month");

                    b.Property<int>("MaxHoursPerEmpMonth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("max_hours_per_emp_month");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER")
                        .HasColumnName("month");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<int>("PeoplePerShift")
                        .HasColumnType("INTEGER")
                        .HasColumnName("people_per_shift");

                    b.Property<string>("ScheduleName")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("schedule_name");

                    b.Property<string>("Shift1Time")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("shift1_time");

                    b.Property<string>("Shift2Time")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("shift2_time");

                    b.Property<int>("ShopId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("shop_id");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex("AvailabilityGroupId")
                        .HasDatabaseName("ix_schedule_preset_avail_group");

                    b.HasIndex("ContainerId")
                        .HasDatabaseName("ix_schedule_preset_container");

                    b.HasIndex("ShopId")
                        .HasDatabaseName("ix_schedule_preset_shop");

                    b.HasIndex("ContainerId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ux_schedule_preset_container_name");

                    b.ToTable("schedule_preset", t =>
                        {
                            t.HasCheckConstraint("ck_schedule_preset_max_consecutive_days", "max_consecutive_days >= 1");

                            t.HasCheckConstraint("ck_schedule_preset_max_consecutive_full", "max_consecutive_full >= 1");

                            t.HasCheckConstraint("ck_schedule_preset_max_full_per_month", "max_full_per_month >= 1");

                            t.HasCheckConstraint("ck_schedule_preset_max_hours_per_emp_month", "max_hours_per_emp_month >= 1");

                            t.HasCheckConstraint("ck_schedule_preset_month", "month BETWEEN 1 AND 12");

                            t.HasCheckConstraint("ck_schedule_preset_people_per_shift", "people_per_shift >= 1");

                            t.HasCheckConstraint("ck_schedule_preset_shift1_format", "shift1_time LIKE '__:__ - __:__'");

                            t.HasCheckConstraint("ck_schedule_preset_shift2_format", "shift2_time LIKE '__:__ - __:__'");
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.ScheduleSlotModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("DayOfMonth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("day_of_month");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("employee_id");

                    b.Property<string>("FromTime")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("from_time");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("schedule_id");

                    b.Property<int>("SlotNo")
                        .HasColumnType("INTEGER")
                        .HasColumnName("slot_no");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("UNFURNISHED")
                        .HasColumnName("status");

                    b.Property<string>("ToTime")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("to_time");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ScheduleId", "DayOfMonth", "FromTime", "ToTime", "EmployeeId")
                        .IsUnique()
                        .HasDatabaseName("ux_slot_unique_emp_per_time")
                        .HasFilter("employee_id IS NOT NULL");

                    b.HasIndex("ScheduleId", "DayOfMonth", "FromTime", "ToTime", "SlotNo")
                        .IsUnique();

                    b.ToTable("schedule_slot", t =>
                        {
                            t.HasCheckConstraint("ck_schedule_slot_dom", "day_of_month BETWEEN 1 AND 31");

                            t.HasCheckConstraint("ck_schedule_slot_slot_no", "slot_no >= 1");

                            t.HasCheckConstraint("ck_schedule_slot_status_pair", "((status='UNFURNISHED' AND employee_id IS NULL) OR (status='ASSIGNED' AND employee_id IS NOT NULL))");

                            t.HasCheckConstraint("ck_schedule_slot_time_format", "from_time LIKE '__:__' AND to_time LIKE '__:__'");

                            t.HasCheckConstraint("ck_schedule_slot_time_order", "from_time < to_time");
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.ShiftSwapHistoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AcceptedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("accepted_at_utc");

                    b.Property<int>("AcceptedByEmployeeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("accepted_by_employee_id");

                    b.Property<string>("AcceptedByEmployeeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("accepted_by_employee_name");

                    b.Property<string>("AfterSnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("after_snapshot_json");

                    b.Property<string>("BeforeSnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("before_snapshot_json");

                    b.Property<string>("ContainerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("container_name");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("DayOfMonth")
                        .HasColumnType("INTEGER")
                        .HasColumnName("day_of_month");

                    b.Property<int?>("FromEmployeeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("from_employee_id");

                    b.Property<string>("FromEmployeeName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("from_employee_name");

                    b.Property<string>("FromTime")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT")
                        .HasColumnName("from_time");

                    b.Property<bool>("IsManagerCreated")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_manager_created");

                    b.Property<int?>("ManualColumnId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("manual_column_id");

                    b.Property<string>("ManualColumnName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("manual_column_name");

                    b.Property<int>("Month")
                        .HasColumnType("INTEGER")
                        .HasColumnName("month");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("schedule_id");

                    b.Property<string>("ScheduleName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("schedule_name");

                    b.Property<int>("ScheduleSlotId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("schedule_slot_id");

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("shop_name");

                    b.Property<int>("SourceShiftSwapRequestId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("source_shift_swap_request_id");

                    b.Property<int?>("TargetEmployeeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("target_employee_id");

                    b.Property<string>("TargetEmployeeName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("target_employee_name");

                    b.Property<string>("ToTime")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT")
                        .HasColumnName("to_time");

                    b.Property<int>("Year")
                        .HasColumnType("INTEGER")
                        .HasColumnName("year");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "ScheduleId", "AcceptedAtUtc" }, "ix_shift_swap_history_schedule_accepted");

                    b.HasIndex(new[] { "SourceShiftSwapRequestId" }, "ux_shift_swap_history_source_request")
                        .IsUnique();

                    b.ToTable("shift_swap_history", t =>
                        {
                            t.HasCheckConstraint("ck_shift_swap_history_dom", "day_of_month BETWEEN 1 AND 31");

                            t.HasCheckConstraint("ck_shift_swap_history_month", "month BETWEEN 1 AND 12");
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.ShiftSwapRequestModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("accepted_at_utc");

                    b.Property<int?>("AcceptedByEmployeeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("accepted_by_employee_id");

                    b.Property<DateTimeOffset?>("CancelledAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("cancelled_at_utc");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<int?>("FromEmployeeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("from_employee_id");

                    b.Property<bool>("IsManagerCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(false)
                        .HasColumnName("is_manager_created");

                    b.Property<int?>("ManualColumnId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("manual_column_id");

                    b.Property<string>("OfferedFromTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("offered_from_time");

                    b.Property<string>("OfferedToTime")
                        .HasColumnType("TEXT")
                        .HasColumnName("offered_to_time");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("schedule_id");

                    b.Property<int>("ScheduleSlotId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("schedule_slot_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Open")
                        .HasColumnName("status");

                    b.Property<int?>("TargetEmployeeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("target_employee_id");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Public")
                        .HasColumnName("visibility");

                    b.HasKey("Id");

                    b.HasIndex("AcceptedByEmployeeId");

                    b.HasIndex("ScheduleSlotId", "Status")
                        .IsUnique()
                        .HasDatabaseName("ux_shift_swap_open_slot")
                        .HasFilter("status = 'Open'");

                    b.HasIndex(new[] { "FromEmployeeId", "Status" }, "ix_shift_swap_from_status");

                    b.HasIndex(new[] { "ScheduleId", "Status" }, "ix_shift_swap_schedule_status");

                    b.HasIndex(new[] { "TargetEmployeeId", "Status" }, "ix_shift_swap_target_status");

                    b.ToTable("shift_swap_request");
                });

            modelBuilder.Entity("DataAccessLayer.Models.ShopModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("address");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ux_shop_name");

                    b.ToTable("shop");
                });

            modelBuilder.Entity("DataAccessLayer.Models.SystemNewsMessageModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Audience")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("audience");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("TEXT")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2800000)
                        .HasColumnType("TEXT")
                        .HasColumnName("image_url");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at_utc");

                    b.Property<string>("VideoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("video_url");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAtUtc")
                        .HasDatabaseName("ix_system_news_created");

                    b.ToTable("system_news_message");
                });

            modelBuilder.Entity("DataAccessLayer.Models.SystemNewsReadModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("account_id");

                    b.Property<string>("AccountRole")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasColumnName("account_role");

                    b.Property<int>("MessageId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("message_id");

                    b.Property<DateTimeOffset>("ReadAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("read_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("AccountRole", "AccountId", "ReadAtUtc")
                        .HasDatabaseName("ix_system_news_read_subject_time");

                    b.HasIndex("MessageId", "AccountRole", "AccountId")
                        .IsUnique()
                        .HasDatabaseName("ux_system_news_read_subject");

                    b.ToTable("system_news_read");
                });

            modelBuilder.Entity("DataAccessLayer.Models.WorkflowLogEntryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .HasColumnName("action");

                    b.Property<int?>("ActorEmployeeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("actor_employee_id");

                    b.Property<string>("ActorName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT")
                        .HasColumnName("actor_name");

                    b.Property<string>("ActorRole")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasColumnName("actor_role");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("occurred_at_utc");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("ix_workflow_log_occurred_at");

                    b.HasIndex("ActorRole", "OccurredAtUtc")
                        .HasDatabaseName("ix_workflow_log_role_time");

                    b.HasIndex(new[] { "OccurredAtUtc" }, "ix_workflow_log_occurred_at");

                    b.HasIndex(new[] { "ActorRole", "OccurredAtUtc" }, "ix_workflow_log_role_time");

                    b.ToTable("workflow_log_entry");
                });

            modelBuilder.Entity("DataAccessLayer.Models.WorkflowLogSettingsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Audience")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("all")
                        .HasColumnName("audience");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(true)
                        .HasColumnName("is_enabled");

                    b.HasKey("Id");

                    b.ToTable("workflow_log_settings", t =>
                        {
                            t.HasCheckConstraint("ck_workflow_log_settings_audience", "audience IN ('all', 'managers', 'employees')");

                            t.HasCheckConstraint("ck_workflow_log_settings_singleton", "id = 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Audience = "all",
                            IsEnabled = true
                        });
                });

            modelBuilder.Entity("DataAccessLayer.Models.AvailabilityGroupDayModel", b =>
                {
                    b.HasOne("DataAccessLayer.Models.AvailabilityGroupMemberModel", "AvailabilityGroupMember")
                        .WithMany("Days")
                        .HasForeignKey("AvailabilityGroupMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AvailabilityGroupMember");
                });

            modelBuilder.Entity("DataAccessLayer.Models.AvailabilityGroupDayTransferModel", b =>
                {
                    b.HasOne("DataAccessLayer.Models.AvailabilityGroupMemberModel", "SourceMember")
                        .WithMany()
                        .HasForeignKey("SourceMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.AvailabilityGroupMemberModel", "TargetMember")
                        .WithMany()
                        .HasForeignKey("TargetMemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SourceMember");

                    b.Navigation("TargetMember");
                });

            modelBuilder.Entity("DataAccessLayer.Models.AvailabilityGroupMemberModel", b =>
                {
                    b.HasOne("DataAccessLayer.Models.AvailabilityGroupModel", "AvailabilityGroup")
                        .WithMany("Members")
                        .HasForeignKey("AvailabilityGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.EmployeeModel", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AvailabilityGroup");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("DataAccessLayer.Models.BindModel", b =>
                {
                    b.HasOne("DataAccessLayer.Models.ManagerAccountModel", "ManagerAccount")
                        .WithMany()
                        .HasForeignKey("ManagerAccountId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ManagerAccount");
                });

            modelBuilder.Entity("DataAccessLayer.Models.CommunicationMessageModel", b =>
                {
                    b.HasOne("DataAccessLayer.Models.ManagerAccountModel", "CreatedByManager")
                        .WithMany()
                        .HasForeignKey("CreatedByManagerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CreatedByManager");
                });

            modelBuilder.Entity("DataAccessLayer.Models.EmployeeAccountModel", b =>
                {
                    b.HasOne("DataAccessLayer.Models.EmployeeModel", "Employee")
                        .WithOne("Account")
                        .HasForeignKey("DataAccessLayer.Models.EmployeeAccountModel", "EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("DataAccessLayer.Models.EmployeeCommunicationDismissalModel", b =>
                {
                    b.HasOne("DataAccessLayer.Models.CommunicationMessageModel", "CommunicationMessage")
                        .WithMany("Dismissals")
                        .HasForeignKey("CommunicationMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.EmployeeModel", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommunicationMessage");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("DataAccessLayer.Models.EmployeeNotificationReadModel", b =>
                {
                    b.HasOne("DataAccessLayer.Models.EmployeeModel", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("DataAccessLayer.Models.EmployeePinnedSwapModel", b =>
                {
                    b.HasOne("DataAccessLayer.Models.EmployeeModel", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.ShiftSwapRequestModel", "ShiftSwap")
                        .WithMany()
                        .HasForeignKey("ShiftSwapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("ShiftSwap");
                });

            modelBuilder.Entity("DataAccessLayer.Models.EmployeeScheduleColumnPreferenceModel", b =>
                {
                    b.HasOne("DataAccessLayer.Models.EmployeeModel", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.ScheduleModel", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("DataAccessLayer.Models.ManagerGraphFillColorBindModel", b =>
                {
                    b.HasOne("DataAccessLayer.Models.ManagerAccountModel", "ManagerAccount")
                        .WithMany()
                        .HasForeignKey("ManagerAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ManagerAccount");
                });

            modelBuilder.Entity("DataAccessLayer.Models.ManagerNoteModel", b =>
                {
                    b.HasOne("DataAccessLayer.Models.ManagerAccountModel", "ManagerAccount")
                        .WithMany()
                        .HasForeignKey("ManagerAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ManagerAccount");
                });

            modelBuilder.Entity("DataAccessLayer.Models.ManagerNotepadStateModel", b =>
                {
                    b.HasOne("DataAccessLayer.Models.ManagerAccountModel", "ManagerAccount")
                        .WithOne()
                        .HasForeignKey("DataAccessLayer.Models.ManagerNotepadStateModel", "ManagerAccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ManagerAccount");
                });

            modelBuilder.Entity("DataAccessLayer.Models.RegulationAcceptanceModel", b =>
                {
                    b.HasOne("DataAccessLayer.Models.RegulationDocumentModel", "RegulationDocument")
                        .WithMany("Acceptances")
                        .HasForeignKey("RegulationDocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RegulationDocument");
                });

            modelBuilder.Entity("DataAccessLayer.Models.ScheduleCellStyleModel", b =>
                {
                    b.HasOne("DataAccessLayer.Models.EmployeeModel", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.ScheduleModel", "Schedule")
                        .WithMany("CellStyles")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("DataAccessLayer.Models.ScheduleEmployeeModel", b =>
                {
                    b.HasOne("DataAccessLayer.Models.EmployeeModel", "Employee")
                        .WithMany("ScheduleEmployees")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.ScheduleModel", "Schedule")
                        .WithMany("Employees")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("DataAccessLayer.Models.ScheduleModel", b =>
                {
                    b.HasOne("DataAccessLayer.Models.AvailabilityGroupModel", "AvailabilityGroup")
                        .WithMany()
                        .HasForeignKey("AvailabilityGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DataAccessLayer.Models.ContainerModel", "Container")
                        .WithMany("Schedules")
                        .HasForeignKey("ContainerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.ShopModel", "Shop")
                        .WithMany("Schedules")
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AvailabilityGroup");

                    b.Navigation("Container");

                    b.Navigation("Shop");
                });

            modelBuilder.Entity("DataAccessLayer.Models.SchedulePresetEmployeeModel", b =>
                {
                    b.HasOne("DataAccessLayer.Models.EmployeeModel", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.SchedulePresetModel", "SchedulePreset")
                        .WithMany("Employees")
                        .HasForeignKey("SchedulePresetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SchedulePreset");
                });

            modelBuilder.Entity("DataAccessLayer.Models.SchedulePresetModel", b =>
                {
                    b.HasOne("DataAccessLayer.Models.AvailabilityGroupModel", null)
                        .WithMany()
                        .HasForeignKey("AvailabilityGroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DataAccessLayer.Models.ContainerModel", null)
                        .WithMany()
                        .HasForeignKey("ContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.ShopModel", null)
                        .WithMany()
                        .HasForeignKey("ShopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccessLayer.Models.ScheduleSlotModel", b =>
                {
                    b.HasOne("DataAccessLayer.Models.EmployeeModel", "Employee")
                        .WithMany("ScheduleSlots")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("DataAccessLayer.Models.ScheduleModel", "Schedule")
                        .WithMany("Slots")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("DataAccessLayer.Models.ShiftSwapHistoryModel", b =>
                {
                    b.HasOne("DataAccessLayer.Models.ScheduleModel", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("DataAccessLayer.Models.ShiftSwapRequestModel", b =>
                {
                    b.HasOne("DataAccessLayer.Models.EmployeeModel", "AcceptedByEmployee")
                        .WithMany()
                        .HasForeignKey("AcceptedByEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DataAccessLayer.Models.EmployeeModel", "FromEmployee")
                        .WithMany()
                        .HasForeignKey("FromEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DataAccessLayer.Models.ScheduleModel", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.ScheduleSlotModel", "ScheduleSlot")
                        .WithMany()
                        .HasForeignKey("ScheduleSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.EmployeeModel", "TargetEmployee")
                        .WithMany()
                        .HasForeignKey("TargetEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AcceptedByEmployee");

                    b.Navigation("FromEmployee");

                    b.Navigation("Schedule");

                    b.Navigation("ScheduleSlot");

                    b.Navigation("TargetEmployee");
                });

            modelBuilder.Entity("DataAccessLayer.Models.SystemNewsReadModel", b =>
                {
                    b.HasOne("DataAccessLayer.Models.SystemNewsMessageModel", "Message")
                        .WithMany("Reads")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");
                });

            modelBuilder.Entity("DataAccessLayer.Models.AvailabilityGroupMemberModel", b =>
                {
                    b.Navigation("Days");
                });

            modelBuilder.Entity("DataAccessLayer.Models.AvailabilityGroupModel", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("DataAccessLayer.Models.CommunicationMessageModel", b =>
                {
                    b.Navigation("Dismissals");
                });

            modelBuilder.Entity("DataAccessLayer.Models.ContainerModel", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("DataAccessLayer.Models.EmployeeModel", b =>
                {
                    b.Navigation("Account");

                    b.Navigation("ScheduleEmployees");

                    b.Navigation("ScheduleSlots");
                });

            modelBuilder.Entity("DataAccessLayer.Models.RegulationDocumentModel", b =>
                {
                    b.Navigation("Acceptances");
                });

            modelBuilder.Entity("DataAccessLayer.Models.ScheduleModel", b =>
                {
                    b.Navigation("CellStyles");

                    b.Navigation("Employees");

                    b.Navigation("Slots");
                });

            modelBuilder.Entity("DataAccessLayer.Models.SchedulePresetModel", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("DataAccessLayer.Models.ShopModel", b =>
                {
                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("DataAccessLayer.Models.SystemNewsMessageModel", b =>
                {
                    b.Navigation("Reads");
                });
#pragma warning restore 612, 618
        }
    }
}
