@host = http://localhost:5055

### Employees - Get all
GET {{host}}/api/employees
Accept: application/json

### Shops - Create
POST {{host}}/api/shops
Content-Type: application/json

{
  "name": "Downtown Shop",
  "address": "Main street 10",
  "description": "Main branch"
}

### Shops - Get all
GET {{host}}/api/shops
Accept: application/json

### Containers - Create
POST {{host}}/api/containers
Content-Type: application/json

{
  "name": "Main Container",
  "note": "Container used in monthly schedules"
}

### Containers - Get all
GET {{host}}/api/containers
Accept: application/json

### AvailabilityGroups - Create
POST {{host}}/api/availability-groups
Content-Type: application/json

{
  "name": "April Team A",
  "year": 2026,
  "month": 4
}

### Graphs - Create graph (schedule)
POST {{host}}/api/containers/1/graphs
Content-Type: application/json

{
  "shopId": 1,
  "name": "April Graph",
  "year": 2026,
  "month": 4,
  "peoplePerShift": 2,
  "shift1Time": "08:00 - 16:00",
  "shift2Time": "16:00 - 23:00",
  "maxHoursPerEmpMonth": 180,
  "maxConsecutiveDays": 5,
  "maxConsecutiveFull": 3,
  "maxFullPerMonth": 10,
  "note": "Schedule graph sample",
  "availabilityGroupId": 1
}

### Graphs - List graphs in container
GET {{host}}/api/containers/1/graphs
Accept: application/json

### Graphs - Get graph by id
GET {{host}}/api/containers/1/graphs/1
Accept: application/json

### Graphs - Update graph
PUT {{host}}/api/containers/1/graphs/1
Content-Type: application/json

{
  "shopId": 1,
  "name": "April Graph Updated",
  "year": 2026,
  "month": 4,
  "peoplePerShift": 3,
  "shift1Time": "08:00 - 16:00",
  "shift2Time": "16:00 - 23:00",
  "maxHoursPerEmpMonth": 170,
  "maxConsecutiveDays": 4,
  "maxConsecutiveFull": 2,
  "maxFullPerMonth": 9,
  "note": "Updated graph",
  "availabilityGroupId": 1
}

### Slots - Create slot
POST {{host}}/api/containers/1/graphs/1/slots
Content-Type: application/json

{
  "dayOfMonth": 5,
  "slotNo": 1,
  "fromTime": "08:00",
  "toTime": "16:00",
  "employeeId": null,
  "status": "UNFURNISHED"
}

### Slots - Get slots
GET {{host}}/api/containers/1/graphs/1/slots
Accept: application/json

### Slots - Update slot (assign employee/status)
PUT {{host}}/api/containers/1/graphs/1/slots/1
Content-Type: application/json

{
  "dayOfMonth": 5,
  "slotNo": 1,
  "fromTime": "08:00",
  "toTime": "16:00",
  "employeeId": 1,
  "status": "ASSIGNED"
}

### Slots - Delete slot
DELETE {{host}}/api/containers/1/graphs/1/slots/1

### Graph employees - Add employee to graph
POST {{host}}/api/containers/1/graphs/1/employees
Content-Type: application/json

{
  "employeeId": 1,
  "minHoursMonth": 120
}

### Graph employees - Get employees in graph
GET {{host}}/api/containers/1/graphs/1/employees
Accept: application/json

### Graph employees - Delete from graph
DELETE {{host}}/api/containers/1/graphs/1/employees/1

### Cell styles - Upsert
PUT {{host}}/api/containers/1/graphs/1/cell-styles
Content-Type: application/json

{
  "dayOfMonth": 5,
  "employeeId": 1,
  "backgroundColorArgb": -16776961,
  "textColorArgb": -1
}

### Cell styles - Get all
GET {{host}}/api/containers/1/graphs/1/cell-styles
Accept: application/json

### Cell styles - Delete by id
DELETE {{host}}/api/containers/1/graphs/1/cell-styles/1
